[QPE-583] avoid negatives
qlik-oss/barsPlus pull request #30
Opened 2019-02-12 08:53 UTC by ahmed-Bazzara

2019-02-13 12:26 UTC, flennmark commented
Looks ok to me. Please merge after code review

2019-02-13 12:27 UTC, flennmark commented
@ahmed-Bazzara : Please solve the conflicts :)

2019-02-14 08:14 UTC, muenva commented
Not sure how to verify this as I have no context what was the issue and how to replicate it @Caele . So I've made 3 scenarios with setting the measures manually. Was it one of them or something else?

1) Measures: 10, -40
---
<img width="1404" alt="measures-10-negative-40" src="https://user-images.githubusercontent.com/2794781/52772453-c866e880-3038-11e9-9ec0-03d4b8fe0d7e.png">


2) Measures: -40, 10
---
<img width="1401" alt="measures-negative-40-10" src="https://user-images.githubusercontent.com/2794781/52772466-cf8df680-3038-11e9-8968-3ec7ffd01ad7.png">


3) Measures: -40, -10
---
<img width="1404" alt="measures-negative-40-neagtive-10" src="https://user-images.githubusercontent.com/2794781/52772475-d583d780-3038-11e9-87a8-d11c10bdf97f.png">

2019-02-19 09:01 UTC, kristofferlind requested changes

2019-02-19 09:01 UTC, kristofferlind commented on src/ldw-barsPlus.js
> +    var max = d3.max(g.data, function (d) {
isn't this block of code identical to the one starting at 447? maybe you could define it once and just pass it in  in both those cases?

2019-02-19 11:28 UTC, kristofferlind approved these changes

2019-02-21 08:52 UTC, merged